apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-single
spec:
  template:
    spec:
      containers:
        - name : main
          image: template-single:develop
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: template-single-configmap
